package onlineTest.action;

import Util.HBSessionDaoImpl;
import com.alibaba.fastjson.JSON;
import com.opensymphony.xwork2.ActionSupport;
import hibernatePOJO.PowerparmMonitor;
import hibernatePOJO.PowerxbMonitor;
import org.apache.struts2.ServletActionContext;
import org.hibernate.mapping.Map;

import javax.servlet.http.HttpServletRequest;
import java.sql.Timestamp;


public class setGenerationDataaction extends ActionSupport {
    private static HBSessionDaoImpl hbsessionDao = new HBSessionDaoImpl();
    private static final long serialVersionUID = 13L;
    private String result;
    private float defzero = 0;

    public String getResult() {
        return result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    /* 根据检测点获取当前电能参数
     */
    public String execute() throws Exception {
        try { //获取数据
            PowerparmMonitor var = new PowerparmMonitor();
            PowerxbMonitor varxb = new PowerxbMonitor();

            HttpServletRequest request = ServletActionContext.getRequest();
            request.setCharacterEncoding("utf-8");

            if (request.getParameter("type").equals("parmData")) {
                var.setDid(request.getParameter("did"));
                var.setTime(Timestamp.valueOf(request.getParameter("time")));

                var.setU1(Float.parseFloat(request.getParameter("u1")));
                var.setU2(Float.parseFloat(request.getParameter("u2")));
                var.setU3(Float.parseFloat(request.getParameter("u3")));
                var.setU4(Float.parseFloat(request.getParameter("u4")));

                var.setI1(Float.parseFloat(request.getParameter("i1")));
                var.setI2(Float.parseFloat(request.getParameter("i2")));
                var.setI3(Float.parseFloat(request.getParameter("i3")));
                var.setI4(Float.parseFloat(request.getParameter("i4")));

                var.setP1(Float.parseFloat(request.getParameter("p1")));
                var.setP2(Float.parseFloat(request.getParameter("p2")));
                var.setP3(Float.parseFloat(request.getParameter("p3")));
                var.setPsum(Float.parseFloat(request.getParameter("pf1")) +
                        Float.parseFloat(request.getParameter("pf2")) +
                        Float.parseFloat(request.getParameter("pf3")));

                var.setQ1(Float.parseFloat(request.getParameter("q1")));
                var.setQ2(Float.parseFloat(request.getParameter("q2")));
                var.setQ3(Float.parseFloat(request.getParameter("q3")));
                var.setQsum(Float.parseFloat(request.getParameter("q1")) +
                        Float.parseFloat(request.getParameter("q2")) +
                        Float.parseFloat(request.getParameter("q3")));

                var.setS1(Float.parseFloat(request.getParameter("s1")));
                var.setS2(Float.parseFloat(request.getParameter("s2")));
                var.setS3(Float.parseFloat(request.getParameter("s3")));
                var.setSsum(Float.parseFloat(request.getParameter("s1")) +
                        Float.parseFloat(request.getParameter("s2")) +
                        Float.parseFloat(request.getParameter("s3")));

                var.setCosPhi1(Float.parseFloat(request.getParameter("cosPhi1")));
                var.setCosPhi2(Float.parseFloat(request.getParameter("cosPhi2")));
                var.setCosPhi3(Float.parseFloat(request.getParameter("cosPhi3")));

                var.setPf1(Float.parseFloat(request.getParameter("pf1")));
                var.setPf2(Float.parseFloat(request.getParameter("pf2")));
                var.setPf3(Float.parseFloat(request.getParameter("pf3")));
                var.setpFsum(Float.parseFloat(request.getParameter("pf1")) +
                        Float.parseFloat(request.getParameter("pf2")) +
                        Float.parseFloat(request.getParameter("pf3")));

                var.setPstU1(Float.parseFloat(request.getParameter("pstU1")));
                var.setPstU2(Float.parseFloat(request.getParameter("pstU2")));
                var.setPstU3(Float.parseFloat(request.getParameter("pstU3")));

                var.setPltU1(Float.parseFloat(request.getParameter("pltU1")));
                var.setPltU2(Float.parseFloat(request.getParameter("pltU2")));
                var.setPltU3(Float.parseFloat(request.getParameter("pltU3")));

                // float defzero = 0;
                var.setIflU1(defzero);
                var.setIflU2(defzero);
                var.setIflU3(defzero);
                var.setIflSum(defzero);

                var.setHz(Float.parseFloat(request.getParameter("hz")));

            } else {
                varxb.setTime(Timestamp.valueOf(request.getParameter("time")));
                varxb.setDid(request.getParameter("did"));

                varxb.setU1Xb1(Float.parseFloat(request.getParameter("u1Xb1")));
                varxb.setU1Xb2(Float.parseFloat(request.getParameter("u1Xb2")));
                varxb.setU1Xb3(Float.parseFloat(request.getParameter("u1Xb3")));
                varxb.setU1Xb4(Float.parseFloat(request.getParameter("u1Xb4")));
                varxb.setU1Xb5(Float.parseFloat(request.getParameter("u1Xb5")));
                varxb.setU1Xb6(Float.parseFloat(request.getParameter("u1Xb6")));
                varxb.setU1Xb7(Float.parseFloat(request.getParameter("u1Xb7")));
                varxb.setU1Xb8(Float.parseFloat(request.getParameter("u1Xb8")));
                varxb.setU1Xb9(Float.parseFloat(request.getParameter("u1Xb9")));
                varxb.setU1Xb10(Float.parseFloat(request.getParameter("u1Xb10")));
                varxb.setU1Xb11(Float.parseFloat(request.getParameter("u1Xb11")));
                varxb.setU1Xb12(Float.parseFloat(request.getParameter("u1Xb12")));
                varxb.setU1Xb13(Float.parseFloat(request.getParameter("u1Xb13")));
                varxb.setU1Xb14(Float.parseFloat(request.getParameter("u1Xb14")));
                varxb.setU1Xb15(Float.parseFloat(request.getParameter("u1Xb15")));
                varxb.setU1Xb16(Float.parseFloat(request.getParameter("u1Xb16")));
                varxb.setU1Xb17(Float.parseFloat(request.getParameter("u1Xb17")));
                varxb.setU1Xb18(Float.parseFloat(request.getParameter("u1Xb18")));
                varxb.setU1Xb19(Float.parseFloat(request.getParameter("u1Xb19")));
                varxb.setU1Xb20(Float.parseFloat(request.getParameter("u1Xb20")));
                varxb.setU1Xb21(Float.parseFloat(request.getParameter("u1Xb21")));
                varxb.setU1Xb22(Float.parseFloat(request.getParameter("u1Xb22")));
                varxb.setU1Xb23(Float.parseFloat(request.getParameter("u1Xb23")));
                varxb.setU1Xb24(Float.parseFloat(request.getParameter("u1Xb24")));
                varxb.setU1Xb25(Float.parseFloat(request.getParameter("u1Xb25")));
                varxb.setU1Xb26(Float.parseFloat(request.getParameter("u1Xb26")));
                varxb.setU1Xb27(Float.parseFloat(request.getParameter("u1Xb27")));
                varxb.setU1Xb28(Float.parseFloat(request.getParameter("u1Xb28")));
                varxb.setU1Xb29(Float.parseFloat(request.getParameter("u1Xb29")));
                varxb.setU1Xb30(Float.parseFloat(request.getParameter("u1Xb30")));
                varxb.setU1Xb31(Float.parseFloat(request.getParameter("u1Xb31")));
                varxb.setU1Xb32(Float.parseFloat(request.getParameter("u1Xb32")));
                varxb.setU1Xb33(Float.parseFloat(request.getParameter("u1Xb33")));
                varxb.setU1Xb34(Float.parseFloat(request.getParameter("u1Xb34")));
                varxb.setU1Xb35(Float.parseFloat(request.getParameter("u1Xb35")));
                varxb.setU1Xb36(Float.parseFloat(request.getParameter("u1Xb36")));
                varxb.setU1Xb37(Float.parseFloat(request.getParameter("u1Xb37")));
                varxb.setU1Xb38(Float.parseFloat(request.getParameter("u1Xb38")));
                varxb.setU1Xb39(Float.parseFloat(request.getParameter("u1Xb39")));
                varxb.setU1Xb40(Float.parseFloat(request.getParameter("u1Xb40")));
                varxb.setU1Xb41(Float.parseFloat(request.getParameter("u1Xb41")));
                varxb.setU1Xb42(Float.parseFloat(request.getParameter("u1Xb42")));
                varxb.setU1Xb43(Float.parseFloat(request.getParameter("u1Xb43")));
                varxb.setU1Xb44(Float.parseFloat(request.getParameter("u1Xb44")));
                varxb.setU1Xb45(Float.parseFloat(request.getParameter("u1Xb45")));
                varxb.setU1Xb46(Float.parseFloat(request.getParameter("u1Xb46")));
                varxb.setU1Xb47(Float.parseFloat(request.getParameter("u1Xb47")));
                varxb.setU1Xb48(Float.parseFloat(request.getParameter("u1Xb48")));
                varxb.setU1Xb49(Float.parseFloat(request.getParameter("u1Xb49")));
                varxb.setU1Xb50(Float.parseFloat(request.getParameter("u1Xb50")));

                varxb.setU2Xb1(Float.parseFloat(request.getParameter("u2Xb1")));
                varxb.setU2Xb2(Float.parseFloat(request.getParameter("u2Xb2")));
                varxb.setU2Xb3(Float.parseFloat(request.getParameter("u2Xb3")));
                varxb.setU2Xb4(Float.parseFloat(request.getParameter("u2Xb4")));
                varxb.setU2Xb5(Float.parseFloat(request.getParameter("u2Xb5")));
                varxb.setU2Xb6(Float.parseFloat(request.getParameter("u2Xb6")));
                varxb.setU2Xb7(Float.parseFloat(request.getParameter("u2Xb7")));
                varxb.setU2Xb8(Float.parseFloat(request.getParameter("u2Xb8")));
                varxb.setU2Xb9(Float.parseFloat(request.getParameter("u2Xb9")));
                varxb.setU2Xb10(Float.parseFloat(request.getParameter("u2Xb10")));
                varxb.setU2Xb11(Float.parseFloat(request.getParameter("u2Xb11")));
                varxb.setU2Xb12(Float.parseFloat(request.getParameter("u2Xb12")));
                varxb.setU2Xb13(Float.parseFloat(request.getParameter("u2Xb13")));
                varxb.setU2Xb14(Float.parseFloat(request.getParameter("u2Xb14")));
                varxb.setU2Xb15(Float.parseFloat(request.getParameter("u2Xb15")));
                varxb.setU2Xb16(Float.parseFloat(request.getParameter("u2Xb16")));
                varxb.setU2Xb17(Float.parseFloat(request.getParameter("u2Xb17")));
                varxb.setU2Xb18(Float.parseFloat(request.getParameter("u2Xb18")));
                varxb.setU2Xb19(Float.parseFloat(request.getParameter("u2Xb19")));
                varxb.setU2Xb20(Float.parseFloat(request.getParameter("u2Xb20")));
                varxb.setU2Xb21(Float.parseFloat(request.getParameter("u2Xb21")));
                varxb.setU2Xb22(Float.parseFloat(request.getParameter("u2Xb22")));
                varxb.setU2Xb23(Float.parseFloat(request.getParameter("u2Xb23")));
                varxb.setU2Xb24(Float.parseFloat(request.getParameter("u2Xb24")));
                varxb.setU2Xb25(Float.parseFloat(request.getParameter("u2Xb25")));
                varxb.setU2Xb26(Float.parseFloat(request.getParameter("u2Xb26")));
                varxb.setU2Xb27(Float.parseFloat(request.getParameter("u2Xb27")));
                varxb.setU2Xb28(Float.parseFloat(request.getParameter("u2Xb28")));
                varxb.setU2Xb29(Float.parseFloat(request.getParameter("u2Xb29")));
                varxb.setU2Xb30(Float.parseFloat(request.getParameter("u2Xb30")));
                varxb.setU2Xb31(Float.parseFloat(request.getParameter("u2Xb31")));
                varxb.setU2Xb32(Float.parseFloat(request.getParameter("u2Xb32")));
                varxb.setU2Xb33(Float.parseFloat(request.getParameter("u2Xb33")));
                varxb.setU2Xb34(Float.parseFloat(request.getParameter("u2Xb34")));
                varxb.setU2Xb35(Float.parseFloat(request.getParameter("u2Xb35")));
                varxb.setU2Xb36(Float.parseFloat(request.getParameter("u2Xb36")));
                varxb.setU2Xb37(Float.parseFloat(request.getParameter("u2Xb37")));
                varxb.setU2Xb38(Float.parseFloat(request.getParameter("u2Xb38")));
                varxb.setU2Xb39(Float.parseFloat(request.getParameter("u2Xb39")));
                varxb.setU2Xb40(Float.parseFloat(request.getParameter("u2Xb40")));
                varxb.setU2Xb41(Float.parseFloat(request.getParameter("u2Xb41")));
                varxb.setU2Xb42(Float.parseFloat(request.getParameter("u2Xb42")));
                varxb.setU2Xb43(Float.parseFloat(request.getParameter("u2Xb43")));
                varxb.setU2Xb44(Float.parseFloat(request.getParameter("u2Xb44")));
                varxb.setU2Xb45(Float.parseFloat(request.getParameter("u2Xb45")));
                varxb.setU2Xb46(Float.parseFloat(request.getParameter("u2Xb46")));
                varxb.setU2Xb47(Float.parseFloat(request.getParameter("u2Xb47")));
                varxb.setU2Xb48(Float.parseFloat(request.getParameter("u2Xb48")));
                varxb.setU2Xb49(Float.parseFloat(request.getParameter("u2Xb49")));
                varxb.setU2Xb50(Float.parseFloat(request.getParameter("u2Xb50")));

                varxb.setU3Xb1(Float.parseFloat(request.getParameter("u3Xb1")));
                varxb.setU3Xb2(Float.parseFloat(request.getParameter("u3Xb2")));
                varxb.setU3Xb3(Float.parseFloat(request.getParameter("u3Xb3")));
                varxb.setU3Xb4(Float.parseFloat(request.getParameter("u3Xb4")));
                varxb.setU3Xb5(Float.parseFloat(request.getParameter("u3Xb5")));
                varxb.setU3Xb6(Float.parseFloat(request.getParameter("u3Xb6")));
                varxb.setU3Xb7(Float.parseFloat(request.getParameter("u3Xb7")));
                varxb.setU3Xb8(Float.parseFloat(request.getParameter("u3Xb8")));
                varxb.setU3Xb9(Float.parseFloat(request.getParameter("u3Xb9")));
                varxb.setU3Xb10(Float.parseFloat(request.getParameter("u3Xb10")));
                varxb.setU3Xb11(Float.parseFloat(request.getParameter("u3Xb11")));
                varxb.setU3Xb12(Float.parseFloat(request.getParameter("u3Xb12")));
                varxb.setU3Xb13(Float.parseFloat(request.getParameter("u3Xb13")));
                varxb.setU3Xb14(Float.parseFloat(request.getParameter("u3Xb14")));
                varxb.setU3Xb15(Float.parseFloat(request.getParameter("u3Xb15")));
                varxb.setU3Xb16(Float.parseFloat(request.getParameter("u3Xb16")));
                varxb.setU3Xb17(Float.parseFloat(request.getParameter("u3Xb17")));
                varxb.setU3Xb18(Float.parseFloat(request.getParameter("u3Xb18")));
                varxb.setU3Xb19(Float.parseFloat(request.getParameter("u3Xb19")));
                varxb.setU3Xb20(Float.parseFloat(request.getParameter("u3Xb20")));
                varxb.setU3Xb21(Float.parseFloat(request.getParameter("u3Xb21")));
                varxb.setU3Xb22(Float.parseFloat(request.getParameter("u3Xb22")));
                varxb.setU3Xb23(Float.parseFloat(request.getParameter("u3Xb23")));
                varxb.setU3Xb24(Float.parseFloat(request.getParameter("u3Xb24")));
                varxb.setU3Xb25(Float.parseFloat(request.getParameter("u3Xb25")));
                varxb.setU3Xb26(Float.parseFloat(request.getParameter("u3Xb26")));
                varxb.setU3Xb27(Float.parseFloat(request.getParameter("u3Xb27")));
                varxb.setU3Xb28(Float.parseFloat(request.getParameter("u3Xb28")));
                varxb.setU3Xb29(Float.parseFloat(request.getParameter("u3Xb29")));
                varxb.setU3Xb30(Float.parseFloat(request.getParameter("u3Xb30")));
                varxb.setU3Xb31(Float.parseFloat(request.getParameter("u3Xb31")));
                varxb.setU3Xb32(Float.parseFloat(request.getParameter("u3Xb32")));
                varxb.setU3Xb33(Float.parseFloat(request.getParameter("u3Xb33")));
                varxb.setU3Xb34(Float.parseFloat(request.getParameter("u3Xb34")));
                varxb.setU3Xb35(Float.parseFloat(request.getParameter("u3Xb35")));
                varxb.setU3Xb36(Float.parseFloat(request.getParameter("u3Xb36")));
                varxb.setU3Xb37(Float.parseFloat(request.getParameter("u3Xb37")));
                varxb.setU3Xb38(Float.parseFloat(request.getParameter("u3Xb38")));
                varxb.setU3Xb39(Float.parseFloat(request.getParameter("u3Xb39")));
                varxb.setU3Xb40(Float.parseFloat(request.getParameter("u3Xb40")));
                varxb.setU3Xb41(Float.parseFloat(request.getParameter("u3Xb41")));
                varxb.setU3Xb42(Float.parseFloat(request.getParameter("u3Xb42")));
                varxb.setU3Xb43(Float.parseFloat(request.getParameter("u3Xb43")));
                varxb.setU3Xb44(Float.parseFloat(request.getParameter("u3Xb44")));
                varxb.setU3Xb45(Float.parseFloat(request.getParameter("u3Xb45")));
                varxb.setU3Xb46(Float.parseFloat(request.getParameter("u3Xb46")));
                varxb.setU3Xb47(Float.parseFloat(request.getParameter("u3Xb47")));
                varxb.setU3Xb48(Float.parseFloat(request.getParameter("u3Xb48")));
                varxb.setU3Xb49(Float.parseFloat(request.getParameter("u3Xb49")));
                varxb.setU3Xb50(Float.parseFloat(request.getParameter("u3Xb50")));

                varxb.setI1Xb1(Float.parseFloat(request.getParameter("i1Xb1")));
                varxb.setI1Xb2(Float.parseFloat(request.getParameter("i1Xb2")));
                varxb.setI1Xb3(Float.parseFloat(request.getParameter("i1Xb3")));
                varxb.setI1Xb4(Float.parseFloat(request.getParameter("i1Xb4")));
                varxb.setI1Xb5(Float.parseFloat(request.getParameter("i1Xb5")));
                varxb.setI1Xb6(Float.parseFloat(request.getParameter("i1Xb6")));
                varxb.setI1Xb7(Float.parseFloat(request.getParameter("i1Xb7")));
                varxb.setI1Xb8(Float.parseFloat(request.getParameter("i1Xb8")));
                varxb.setI1Xb9(Float.parseFloat(request.getParameter("i1Xb9")));
                varxb.setI1Xb10(Float.parseFloat(request.getParameter("i1Xb10")));
                varxb.setI1Xb11(Float.parseFloat(request.getParameter("i1Xb11")));
                varxb.setI1Xb12(Float.parseFloat(request.getParameter("i1Xb12")));
                varxb.setI1Xb13(Float.parseFloat(request.getParameter("i1Xb13")));
                varxb.setI1Xb14(Float.parseFloat(request.getParameter("i1Xb14")));
                varxb.setI1Xb15(Float.parseFloat(request.getParameter("i1Xb15")));
                varxb.setI1Xb16(Float.parseFloat(request.getParameter("i1Xb16")));
                varxb.setI1Xb17(Float.parseFloat(request.getParameter("i1Xb17")));
                varxb.setI1Xb18(Float.parseFloat(request.getParameter("i1Xb18")));
                varxb.setI1Xb19(Float.parseFloat(request.getParameter("i1Xb19")));
                varxb.setI1Xb20(Float.parseFloat(request.getParameter("i1Xb20")));
                varxb.setI1Xb21(Float.parseFloat(request.getParameter("i1Xb21")));
                varxb.setI1Xb22(Float.parseFloat(request.getParameter("i1Xb22")));
                varxb.setI1Xb23(Float.parseFloat(request.getParameter("i1Xb23")));
                varxb.setI1Xb24(Float.parseFloat(request.getParameter("i1Xb24")));
                varxb.setI1Xb25(Float.parseFloat(request.getParameter("i1Xb25")));
                varxb.setI1Xb26(Float.parseFloat(request.getParameter("i1Xb26")));
                varxb.setI1Xb27(Float.parseFloat(request.getParameter("i1Xb27")));
                varxb.setI1Xb28(Float.parseFloat(request.getParameter("i1Xb28")));
                varxb.setI1Xb29(Float.parseFloat(request.getParameter("i1Xb29")));
                varxb.setI1Xb30(Float.parseFloat(request.getParameter("i1Xb30")));
                varxb.setI1Xb31(Float.parseFloat(request.getParameter("i1Xb31")));
                varxb.setI1Xb32(Float.parseFloat(request.getParameter("i1Xb32")));
                varxb.setI1Xb33(Float.parseFloat(request.getParameter("i1Xb33")));
                varxb.setI1Xb34(Float.parseFloat(request.getParameter("i1Xb34")));
                varxb.setI1Xb35(Float.parseFloat(request.getParameter("i1Xb35")));
                varxb.setI1Xb36(Float.parseFloat(request.getParameter("i1Xb36")));
                varxb.setI1Xb37(Float.parseFloat(request.getParameter("i1Xb37")));
                varxb.setI1Xb38(Float.parseFloat(request.getParameter("i1Xb38")));
                varxb.setI1Xb39(Float.parseFloat(request.getParameter("i1Xb39")));
                varxb.setI1Xb40(Float.parseFloat(request.getParameter("i1Xb40")));
                varxb.setI1Xb41(Float.parseFloat(request.getParameter("i1Xb41")));
                varxb.setI1Xb42(Float.parseFloat(request.getParameter("i1Xb42")));
                varxb.setI1Xb43(Float.parseFloat(request.getParameter("i1Xb43")));
                varxb.setI1Xb44(Float.parseFloat(request.getParameter("i1Xb44")));
                varxb.setI1Xb45(Float.parseFloat(request.getParameter("i1Xb45")));
                varxb.setI1Xb46(Float.parseFloat(request.getParameter("i1Xb46")));
                varxb.setI1Xb47(Float.parseFloat(request.getParameter("i1Xb47")));
                varxb.setI1Xb48(Float.parseFloat(request.getParameter("i1Xb48")));
                varxb.setI1Xb49(Float.parseFloat(request.getParameter("i1Xb49")));
                varxb.setI1Xb50(defzero);

                varxb.setI2Xb1(Float.parseFloat(request.getParameter("i2Xb1")));
                varxb.setI2Xb2(Float.parseFloat(request.getParameter("i2Xb2")));
                varxb.setI2Xb3(Float.parseFloat(request.getParameter("i2Xb3")));
                varxb.setI2Xb4(Float.parseFloat(request.getParameter("i2Xb4")));
                varxb.setI2Xb5(Float.parseFloat(request.getParameter("i2Xb5")));
                varxb.setI2Xb6(Float.parseFloat(request.getParameter("i2Xb6")));
                varxb.setI2Xb7(Float.parseFloat(request.getParameter("i2Xb7")));
                varxb.setI2Xb8(Float.parseFloat(request.getParameter("i2Xb8")));
                varxb.setI2Xb9(Float.parseFloat(request.getParameter("i2Xb9")));
                varxb.setI2Xb10(Float.parseFloat(request.getParameter("i2Xb10")));
                varxb.setI2Xb11(Float.parseFloat(request.getParameter("i2Xb11")));
                varxb.setI2Xb12(Float.parseFloat(request.getParameter("i2Xb12")));
                varxb.setI2Xb13(Float.parseFloat(request.getParameter("i2Xb13")));
                varxb.setI2Xb14(Float.parseFloat(request.getParameter("i2Xb14")));
                varxb.setI2Xb15(Float.parseFloat(request.getParameter("i2Xb15")));
                varxb.setI2Xb16(Float.parseFloat(request.getParameter("i2Xb16")));
                varxb.setI2Xb17(Float.parseFloat(request.getParameter("i2Xb17")));
                varxb.setI2Xb18(Float.parseFloat(request.getParameter("i2Xb18")));
                varxb.setI2Xb19(Float.parseFloat(request.getParameter("i2Xb19")));
                varxb.setI2Xb20(Float.parseFloat(request.getParameter("i2Xb20")));
                varxb.setI2Xb21(Float.parseFloat(request.getParameter("i2Xb21")));
                varxb.setI2Xb22(Float.parseFloat(request.getParameter("i2Xb22")));
                varxb.setI2Xb23(Float.parseFloat(request.getParameter("i2Xb23")));
                varxb.setI2Xb24(Float.parseFloat(request.getParameter("i2Xb24")));
                varxb.setI2Xb25(Float.parseFloat(request.getParameter("i2Xb25")));
                varxb.setI2Xb26(Float.parseFloat(request.getParameter("i2Xb26")));
                varxb.setI2Xb27(Float.parseFloat(request.getParameter("i2Xb27")));
                varxb.setI2Xb28(Float.parseFloat(request.getParameter("i2Xb28")));
                varxb.setI2Xb29(Float.parseFloat(request.getParameter("i2Xb29")));
                varxb.setI2Xb30(Float.parseFloat(request.getParameter("i2Xb30")));
                varxb.setI2Xb31(Float.parseFloat(request.getParameter("i2Xb31")));
                varxb.setI2Xb32(Float.parseFloat(request.getParameter("i2Xb32")));
                varxb.setI2Xb33(Float.parseFloat(request.getParameter("i2Xb33")));
                varxb.setI2Xb34(Float.parseFloat(request.getParameter("i2Xb34")));
                varxb.setI2Xb35(Float.parseFloat(request.getParameter("i2Xb35")));
                varxb.setI2Xb36(Float.parseFloat(request.getParameter("i2Xb36")));
                varxb.setI2Xb37(Float.parseFloat(request.getParameter("i2Xb37")));
                varxb.setI2Xb38(Float.parseFloat(request.getParameter("i2Xb38")));
                varxb.setI2Xb39(Float.parseFloat(request.getParameter("i2Xb39")));
                varxb.setI2Xb40(Float.parseFloat(request.getParameter("i2Xb40")));
                varxb.setI2Xb41(Float.parseFloat(request.getParameter("i2Xb41")));
                varxb.setI2Xb42(Float.parseFloat(request.getParameter("i2Xb42")));
                varxb.setI2Xb43(Float.parseFloat(request.getParameter("i2Xb43")));
                varxb.setI2Xb44(Float.parseFloat(request.getParameter("i2Xb44")));
                varxb.setI2Xb45(Float.parseFloat(request.getParameter("i2Xb45")));
                varxb.setI2Xb46(Float.parseFloat(request.getParameter("i2Xb46")));
                varxb.setI2Xb47(Float.parseFloat(request.getParameter("i2Xb47")));
                varxb.setI2Xb48(Float.parseFloat(request.getParameter("i2Xb48")));
                varxb.setI2Xb49(Float.parseFloat(request.getParameter("i2Xb49")));
                varxb.setI2Xb50(defzero);

                varxb.setI3Xb1(Float.parseFloat(request.getParameter("i3Xb1")));
                varxb.setI3Xb2(Float.parseFloat(request.getParameter("i3Xb2")));
                varxb.setI3Xb3(Float.parseFloat(request.getParameter("i3Xb3")));
                varxb.setI3Xb4(Float.parseFloat(request.getParameter("i3Xb4")));
                varxb.setI3Xb5(Float.parseFloat(request.getParameter("i3Xb5")));
                varxb.setI3Xb6(Float.parseFloat(request.getParameter("i3Xb6")));
                varxb.setI3Xb7(Float.parseFloat(request.getParameter("i3Xb7")));
                varxb.setI3Xb8(Float.parseFloat(request.getParameter("i3Xb8")));
                varxb.setI3Xb9(Float.parseFloat(request.getParameter("i3Xb9")));
                varxb.setI3Xb10(Float.parseFloat(request.getParameter("i3Xb10")));
                varxb.setI3Xb11(Float.parseFloat(request.getParameter("i3Xb11")));
                varxb.setI3Xb12(Float.parseFloat(request.getParameter("i3Xb12")));
                varxb.setI3Xb13(Float.parseFloat(request.getParameter("i3Xb13")));
                varxb.setI3Xb14(Float.parseFloat(request.getParameter("i3Xb14")));
                varxb.setI3Xb15(Float.parseFloat(request.getParameter("i3Xb15")));
                varxb.setI3Xb16(Float.parseFloat(request.getParameter("i3Xb16")));
                varxb.setI3Xb17(Float.parseFloat(request.getParameter("i3Xb17")));
                varxb.setI3Xb18(Float.parseFloat(request.getParameter("i3Xb18")));
                varxb.setI3Xb19(Float.parseFloat(request.getParameter("i3Xb19")));
                varxb.setI3Xb20(Float.parseFloat(request.getParameter("i3Xb20")));
                varxb.setI3Xb21(Float.parseFloat(request.getParameter("i3Xb21")));
                varxb.setI3Xb22(Float.parseFloat(request.getParameter("i3Xb22")));
                varxb.setI3Xb23(Float.parseFloat(request.getParameter("i3Xb23")));
                varxb.setI3Xb24(Float.parseFloat(request.getParameter("i3Xb24")));
                varxb.setI3Xb25(Float.parseFloat(request.getParameter("i3Xb25")));
                varxb.setI3Xb26(Float.parseFloat(request.getParameter("i3Xb26")));
                varxb.setI3Xb27(Float.parseFloat(request.getParameter("i3Xb27")));
                varxb.setI3Xb28(Float.parseFloat(request.getParameter("i3Xb28")));
                varxb.setI3Xb29(Float.parseFloat(request.getParameter("i3Xb29")));
                varxb.setI3Xb30(Float.parseFloat(request.getParameter("i3Xb30")));
                varxb.setI3Xb31(Float.parseFloat(request.getParameter("i3Xb31")));
                varxb.setI3Xb32(Float.parseFloat(request.getParameter("i3Xb32")));
                varxb.setI3Xb33(Float.parseFloat(request.getParameter("i3Xb33")));
                varxb.setI3Xb34(Float.parseFloat(request.getParameter("i3Xb34")));
                varxb.setI3Xb35(Float.parseFloat(request.getParameter("i3Xb35")));
                varxb.setI3Xb36(Float.parseFloat(request.getParameter("i3Xb36")));
                varxb.setI3Xb37(Float.parseFloat(request.getParameter("i3Xb37")));
                varxb.setI3Xb38(Float.parseFloat(request.getParameter("i3Xb38")));
                varxb.setI3Xb39(Float.parseFloat(request.getParameter("i3Xb39")));
                varxb.setI3Xb40(Float.parseFloat(request.getParameter("i3Xb40")));
                varxb.setI3Xb41(Float.parseFloat(request.getParameter("i3Xb41")));
                varxb.setI3Xb42(Float.parseFloat(request.getParameter("i3Xb42")));
                varxb.setI3Xb43(Float.parseFloat(request.getParameter("i3Xb43")));
                varxb.setI3Xb44(Float.parseFloat(request.getParameter("i3Xb44")));
                varxb.setI3Xb45(Float.parseFloat(request.getParameter("i3Xb45")));
                varxb.setI3Xb46(Float.parseFloat(request.getParameter("i3Xb46")));
                varxb.setI3Xb47(Float.parseFloat(request.getParameter("i3Xb47")));
                varxb.setI3Xb48(Float.parseFloat(request.getParameter("i3Xb48")));
                varxb.setI3Xb49(Float.parseFloat(request.getParameter("i3Xb49")));
                varxb.setI3Xb50(defzero);

                varxb.setU1Va2(Float.parseFloat(request.getParameter("u1Va2")));
                varxb.setU1Va3(Float.parseFloat(request.getParameter("u1Va3")));
                varxb.setU1Va4(Float.parseFloat(request.getParameter("u1Va4")));
                varxb.setU1Va5(Float.parseFloat(request.getParameter("u1Va5")));
                varxb.setU1Va6(Float.parseFloat(request.getParameter("u1Va6")));
                varxb.setU1Va7(Float.parseFloat(request.getParameter("u1Va7")));
                varxb.setU1Va8(Float.parseFloat(request.getParameter("u1Va8")));
                varxb.setU1Va9(Float.parseFloat(request.getParameter("u1Va9")));
                varxb.setU1Va10(Float.parseFloat(request.getParameter("u1Va10")));
                varxb.setU1Va11(Float.parseFloat(request.getParameter("u1Va11")));
                varxb.setU1Va12(Float.parseFloat(request.getParameter("u1Va12")));
                varxb.setU1Va13(Float.parseFloat(request.getParameter("u1Va13")));
                varxb.setU1Va14(Float.parseFloat(request.getParameter("u1Va14")));
                varxb.setU1Va15(Float.parseFloat(request.getParameter("u1Va15")));
                varxb.setU1Va16(Float.parseFloat(request.getParameter("u1Va16")));
                varxb.setU1Va17(Float.parseFloat(request.getParameter("u1Va17")));
                varxb.setU1Va18(Float.parseFloat(request.getParameter("u1Va18")));
                varxb.setU1Va19(Float.parseFloat(request.getParameter("u1Va19")));
                varxb.setU1Va20(Float.parseFloat(request.getParameter("u1Va20")));
                varxb.setU1Va21(Float.parseFloat(request.getParameter("u1Va21")));
                varxb.setU1Va22(Float.parseFloat(request.getParameter("u1Va22")));
                varxb.setU1Va23(Float.parseFloat(request.getParameter("u1Va23")));
                varxb.setU1Va24(Float.parseFloat(request.getParameter("u1Va24")));
                varxb.setU1Va25(Float.parseFloat(request.getParameter("u1Va25")));
                varxb.setU1Va26(Float.parseFloat(request.getParameter("u1Va26")));
                varxb.setU1Va27(Float.parseFloat(request.getParameter("u1Va27")));
                varxb.setU1Va28(Float.parseFloat(request.getParameter("u1Va28")));
                varxb.setU1Va29(Float.parseFloat(request.getParameter("u1Va29")));
                varxb.setU1Va30(Float.parseFloat(request.getParameter("u1Va30")));
                varxb.setU1Va31(Float.parseFloat(request.getParameter("u1Va31")));
                varxb.setU1Va32(Float.parseFloat(request.getParameter("u1Va32")));
                varxb.setU1Va33(Float.parseFloat(request.getParameter("u1Va33")));
                varxb.setU1Va34(Float.parseFloat(request.getParameter("u1Va34")));
                varxb.setU1Va35(Float.parseFloat(request.getParameter("u1Va35")));
                varxb.setU1Va36(Float.parseFloat(request.getParameter("u1Va36")));
                varxb.setU1Va37(Float.parseFloat(request.getParameter("u1Va37")));
                varxb.setU1Va38(Float.parseFloat(request.getParameter("u1Va38")));
                varxb.setU1Va39(Float.parseFloat(request.getParameter("u1Va39")));
                varxb.setU1Va40(Float.parseFloat(request.getParameter("u1Va40")));
                varxb.setU1Va41(Float.parseFloat(request.getParameter("u1Va41")));
                varxb.setU1Va42(Float.parseFloat(request.getParameter("u1Va42")));
                varxb.setU1Va43(Float.parseFloat(request.getParameter("u1Va43")));
                varxb.setU1Va44(Float.parseFloat(request.getParameter("u1Va44")));
                varxb.setU1Va45(Float.parseFloat(request.getParameter("u1Va45")));
                varxb.setU1Va46(Float.parseFloat(request.getParameter("u1Va46")));
                varxb.setU1Va47(Float.parseFloat(request.getParameter("u1Va47")));
                varxb.setU1Va48(Float.parseFloat(request.getParameter("u1Va48")));
                varxb.setU1Va49(Float.parseFloat(request.getParameter("u1Va49")));
                varxb.setU1Va50(Float.parseFloat(request.getParameter("u1Va50")));

                varxb.setU2Va2(Float.parseFloat(request.getParameter("u2Va2")));
                varxb.setU2Va3(Float.parseFloat(request.getParameter("u2Va3")));
                varxb.setU2Va4(Float.parseFloat(request.getParameter("u2Va4")));
                varxb.setU2Va5(Float.parseFloat(request.getParameter("u2Va5")));
                varxb.setU2Va6(Float.parseFloat(request.getParameter("u2Va6")));
                varxb.setU2Va7(Float.parseFloat(request.getParameter("u2Va7")));
                varxb.setU2Va8(Float.parseFloat(request.getParameter("u2Va8")));
                varxb.setU2Va9(Float.parseFloat(request.getParameter("u2Va9")));
                varxb.setU2Va10(Float.parseFloat(request.getParameter("u2Va10")));
                varxb.setU2Va11(Float.parseFloat(request.getParameter("u2Va11")));
                varxb.setU2Va12(Float.parseFloat(request.getParameter("u2Va12")));
                varxb.setU2Va13(Float.parseFloat(request.getParameter("u2Va13")));
                varxb.setU2Va14(Float.parseFloat(request.getParameter("u2Va14")));
                varxb.setU2Va15(Float.parseFloat(request.getParameter("u2Va15")));
                varxb.setU2Va16(Float.parseFloat(request.getParameter("u2Va16")));
                varxb.setU2Va17(Float.parseFloat(request.getParameter("u2Va17")));
                varxb.setU2Va18(Float.parseFloat(request.getParameter("u2Va18")));
                varxb.setU2Va19(Float.parseFloat(request.getParameter("u2Va19")));
                varxb.setU2Va20(Float.parseFloat(request.getParameter("u2Va20")));
                varxb.setU2Va21(Float.parseFloat(request.getParameter("u2Va21")));
                varxb.setU2Va22(Float.parseFloat(request.getParameter("u2Va22")));
                varxb.setU2Va23(Float.parseFloat(request.getParameter("u2Va23")));
                varxb.setU2Va24(Float.parseFloat(request.getParameter("u2Va24")));
                varxb.setU2Va25(Float.parseFloat(request.getParameter("u2Va25")));
                varxb.setU2Va26(Float.parseFloat(request.getParameter("u2Va26")));
                varxb.setU2Va27(Float.parseFloat(request.getParameter("u2Va27")));
                varxb.setU2Va28(Float.parseFloat(request.getParameter("u2Va28")));
                varxb.setU2Va29(Float.parseFloat(request.getParameter("u2Va29")));
                varxb.setU2Va30(Float.parseFloat(request.getParameter("u2Va30")));
                varxb.setU2Va31(Float.parseFloat(request.getParameter("u2Va31")));
                varxb.setU2Va32(Float.parseFloat(request.getParameter("u2Va32")));
                varxb.setU2Va33(Float.parseFloat(request.getParameter("u2Va33")));
                varxb.setU2Va34(Float.parseFloat(request.getParameter("u2Va34")));
                varxb.setU2Va35(Float.parseFloat(request.getParameter("u2Va35")));
                varxb.setU2Va36(Float.parseFloat(request.getParameter("u2Va36")));
                varxb.setU2Va37(Float.parseFloat(request.getParameter("u2Va37")));
                varxb.setU2Va38(Float.parseFloat(request.getParameter("u2Va38")));
                varxb.setU2Va39(Float.parseFloat(request.getParameter("u2Va39")));
                varxb.setU2Va40(Float.parseFloat(request.getParameter("u2Va40")));
                varxb.setU2Va41(Float.parseFloat(request.getParameter("u2Va41")));
                varxb.setU2Va42(Float.parseFloat(request.getParameter("u2Va42")));
                varxb.setU2Va43(Float.parseFloat(request.getParameter("u2Va43")));
                varxb.setU2Va44(Float.parseFloat(request.getParameter("u2Va44")));
                varxb.setU2Va45(Float.parseFloat(request.getParameter("u2Va45")));
                varxb.setU2Va46(Float.parseFloat(request.getParameter("u2Va46")));
                varxb.setU2Va47(Float.parseFloat(request.getParameter("u2Va47")));
                varxb.setU2Va48(Float.parseFloat(request.getParameter("u2Va48")));
                varxb.setU2Va49(Float.parseFloat(request.getParameter("u2Va49")));
                varxb.setU2Va50(Float.parseFloat(request.getParameter("u2Va50")));

                varxb.setU3Va2(Float.parseFloat(request.getParameter("u3Va2")));
                varxb.setU3Va3(Float.parseFloat(request.getParameter("u3Va3")));
                varxb.setU3Va4(Float.parseFloat(request.getParameter("u3Va4")));
                varxb.setU3Va5(Float.parseFloat(request.getParameter("u3Va5")));
                varxb.setU3Va6(Float.parseFloat(request.getParameter("u3Va6")));
                varxb.setU3Va7(Float.parseFloat(request.getParameter("u3Va7")));
                varxb.setU3Va8(Float.parseFloat(request.getParameter("u3Va8")));
                varxb.setU3Va9(Float.parseFloat(request.getParameter("u3Va9")));
                varxb.setU3Va10(Float.parseFloat(request.getParameter("u3Va10")));
                varxb.setU3Va11(Float.parseFloat(request.getParameter("u3Va11")));
                varxb.setU3Va12(Float.parseFloat(request.getParameter("u3Va12")));
                varxb.setU3Va13(Float.parseFloat(request.getParameter("u3Va13")));
                varxb.setU3Va14(Float.parseFloat(request.getParameter("u3Va14")));
                varxb.setU3Va15(Float.parseFloat(request.getParameter("u3Va15")));
                varxb.setU3Va16(Float.parseFloat(request.getParameter("u3Va16")));
                varxb.setU3Va17(Float.parseFloat(request.getParameter("u3Va17")));
                varxb.setU3Va18(Float.parseFloat(request.getParameter("u3Va18")));
                varxb.setU3Va19(Float.parseFloat(request.getParameter("u3Va19")));
                varxb.setU3Va20(Float.parseFloat(request.getParameter("u3Va20")));
                varxb.setU3Va21(Float.parseFloat(request.getParameter("u3Va21")));
                varxb.setU3Va22(Float.parseFloat(request.getParameter("u3Va22")));
                varxb.setU3Va23(Float.parseFloat(request.getParameter("u3Va23")));
                varxb.setU3Va24(Float.parseFloat(request.getParameter("u3Va24")));
                varxb.setU3Va25(Float.parseFloat(request.getParameter("u3Va25")));
                varxb.setU3Va26(Float.parseFloat(request.getParameter("u3Va26")));
                varxb.setU3Va27(Float.parseFloat(request.getParameter("u3Va27")));
                varxb.setU3Va28(Float.parseFloat(request.getParameter("u3Va28")));
                varxb.setU3Va29(Float.parseFloat(request.getParameter("u3Va29")));
                varxb.setU3Va30(Float.parseFloat(request.getParameter("u3Va30")));
                varxb.setU3Va31(Float.parseFloat(request.getParameter("u3Va31")));
                varxb.setU3Va32(Float.parseFloat(request.getParameter("u3Va32")));
                varxb.setU3Va33(Float.parseFloat(request.getParameter("u3Va33")));
                varxb.setU3Va34(Float.parseFloat(request.getParameter("u3Va34")));
                varxb.setU3Va35(Float.parseFloat(request.getParameter("u3Va35")));
                varxb.setU3Va36(Float.parseFloat(request.getParameter("u3Va36")));
                varxb.setU3Va37(Float.parseFloat(request.getParameter("u3Va37")));
                varxb.setU3Va38(Float.parseFloat(request.getParameter("u3Va38")));
                varxb.setU3Va39(Float.parseFloat(request.getParameter("u3Va39")));
                varxb.setU3Va40(Float.parseFloat(request.getParameter("u3Va40")));
                varxb.setU3Va41(Float.parseFloat(request.getParameter("u3Va41")));
                varxb.setU3Va42(Float.parseFloat(request.getParameter("u3Va42")));
                varxb.setU3Va43(Float.parseFloat(request.getParameter("u3Va43")));
                varxb.setU3Va44(Float.parseFloat(request.getParameter("u3Va44")));
                varxb.setU3Va45(Float.parseFloat(request.getParameter("u3Va45")));
                varxb.setU3Va46(Float.parseFloat(request.getParameter("u3Va46")));
                varxb.setU3Va47(Float.parseFloat(request.getParameter("u3Va47")));
                varxb.setU3Va48(Float.parseFloat(request.getParameter("u3Va48")));
                varxb.setU3Va49(Float.parseFloat(request.getParameter("u3Va49")));
                varxb.setU3Va50(Float.parseFloat(request.getParameter("u3Va50")));

                varxb.setI1Va2(Float.parseFloat(request.getParameter("i1Va2")));
                varxb.setI1Va3(Float.parseFloat(request.getParameter("i1Va3")));
                varxb.setI1Va4(Float.parseFloat(request.getParameter("i1Va4")));
                varxb.setI1Va5(Float.parseFloat(request.getParameter("i1Va5")));
                varxb.setI1Va6(Float.parseFloat(request.getParameter("i1Va6")));
                varxb.setI1Va7(Float.parseFloat(request.getParameter("i1Va7")));
                varxb.setI1Va8(Float.parseFloat(request.getParameter("i1Va8")));
                varxb.setI1Va9(Float.parseFloat(request.getParameter("i1Va9")));
                varxb.setI1Va10(Float.parseFloat(request.getParameter("i1Va10")));
                varxb.setI1Va11(Float.parseFloat(request.getParameter("i1Va11")));
                varxb.setI1Va12(Float.parseFloat(request.getParameter("i1Va12")));
                varxb.setI1Va13(Float.parseFloat(request.getParameter("i1Va13")));
                varxb.setI1Va14(Float.parseFloat(request.getParameter("i1Va14")));
                varxb.setI1Va15(Float.parseFloat(request.getParameter("i1Va15")));
                varxb.setI1Va16(Float.parseFloat(request.getParameter("i1Va16")));
                varxb.setI1Va17(Float.parseFloat(request.getParameter("i1Va17")));
                varxb.setI1Va18(Float.parseFloat(request.getParameter("i1Va18")));
                varxb.setI1Va19(Float.parseFloat(request.getParameter("i1Va19")));
                varxb.setI1Va20(Float.parseFloat(request.getParameter("i1Va20")));
                varxb.setI1Va21(Float.parseFloat(request.getParameter("i1Va21")));
                varxb.setI1Va22(Float.parseFloat(request.getParameter("i1Va22")));
                varxb.setI1Va23(Float.parseFloat(request.getParameter("i1Va23")));
                varxb.setI1Va24(Float.parseFloat(request.getParameter("i1Va24")));
                varxb.setI1Va25(Float.parseFloat(request.getParameter("i1Va25")));
                varxb.setI1Va26(Float.parseFloat(request.getParameter("i1Va26")));
                varxb.setI1Va27(Float.parseFloat(request.getParameter("i1Va27")));
                varxb.setI1Va28(Float.parseFloat(request.getParameter("i1Va28")));
                varxb.setI1Va29(Float.parseFloat(request.getParameter("i1Va29")));
                varxb.setI1Va30(Float.parseFloat(request.getParameter("i1Va30")));
                varxb.setI1Va31(Float.parseFloat(request.getParameter("i1Va31")));
                varxb.setI1Va32(Float.parseFloat(request.getParameter("i1Va32")));
                varxb.setI1Va33(Float.parseFloat(request.getParameter("i1Va33")));
                varxb.setI1Va34(Float.parseFloat(request.getParameter("i1Va34")));
                varxb.setI1Va35(Float.parseFloat(request.getParameter("i1Va35")));
                varxb.setI1Va36(Float.parseFloat(request.getParameter("i1Va36")));
                varxb.setI1Va37(Float.parseFloat(request.getParameter("i1Va37")));
                varxb.setI1Va38(Float.parseFloat(request.getParameter("i1Va38")));
                varxb.setI1Va39(Float.parseFloat(request.getParameter("i1Va39")));
                varxb.setI1Va40(Float.parseFloat(request.getParameter("i1Va40")));
                varxb.setI1Va41(Float.parseFloat(request.getParameter("i1Va41")));
                varxb.setI1Va42(Float.parseFloat(request.getParameter("i1Va42")));
                varxb.setI1Va43(Float.parseFloat(request.getParameter("i1Va43")));
                varxb.setI1Va44(Float.parseFloat(request.getParameter("i1Va44")));
                varxb.setI1Va45(Float.parseFloat(request.getParameter("i1Va45")));
                varxb.setI1Va46(Float.parseFloat(request.getParameter("i1Va46")));
                varxb.setI1Va47(Float.parseFloat(request.getParameter("i1Va47")));
                varxb.setI1Va48(Float.parseFloat(request.getParameter("i1Va48")));
                varxb.setI1Va49(Float.parseFloat(request.getParameter("i1Va49")));
                varxb.setI1Va50(Float.parseFloat(request.getParameter("i1Va50")));

                varxb.setI2Va2(Float.parseFloat(request.getParameter("i2Va2")));
                varxb.setI2Va3(Float.parseFloat(request.getParameter("i2Va3")));
                varxb.setI2Va4(Float.parseFloat(request.getParameter("i2Va4")));
                varxb.setI2Va5(Float.parseFloat(request.getParameter("i2Va5")));
                varxb.setI2Va6(Float.parseFloat(request.getParameter("i2Va6")));
                varxb.setI2Va7(Float.parseFloat(request.getParameter("i2Va7")));
                varxb.setI2Va8(Float.parseFloat(request.getParameter("i2Va8")));
                varxb.setI2Va9(Float.parseFloat(request.getParameter("i2Va9")));
                varxb.setI2Va10(Float.parseFloat(request.getParameter("i2Va10")));
                varxb.setI2Va11(Float.parseFloat(request.getParameter("i2Va11")));
                varxb.setI2Va12(Float.parseFloat(request.getParameter("i2Va12")));
                varxb.setI2Va13(Float.parseFloat(request.getParameter("i2Va13")));
                varxb.setI2Va14(Float.parseFloat(request.getParameter("i2Va14")));
                varxb.setI2Va15(Float.parseFloat(request.getParameter("i2Va15")));
                varxb.setI2Va16(Float.parseFloat(request.getParameter("i2Va16")));
                varxb.setI2Va17(Float.parseFloat(request.getParameter("i2Va17")));
                varxb.setI2Va18(Float.parseFloat(request.getParameter("i2Va18")));
                varxb.setI2Va19(Float.parseFloat(request.getParameter("i2Va19")));
                varxb.setI2Va20(Float.parseFloat(request.getParameter("i2Va20")));
                varxb.setI2Va21(Float.parseFloat(request.getParameter("i2Va21")));
                varxb.setI2Va22(Float.parseFloat(request.getParameter("i2Va22")));
                varxb.setI2Va23(Float.parseFloat(request.getParameter("i2Va23")));
                varxb.setI2Va24(Float.parseFloat(request.getParameter("i2Va24")));
                varxb.setI2Va25(Float.parseFloat(request.getParameter("i2Va25")));
                varxb.setI2Va26(Float.parseFloat(request.getParameter("i2Va26")));
                varxb.setI2Va27(Float.parseFloat(request.getParameter("i2Va27")));
                varxb.setI2Va28(Float.parseFloat(request.getParameter("i2Va28")));
                varxb.setI2Va29(Float.parseFloat(request.getParameter("i2Va29")));
                varxb.setI2Va30(Float.parseFloat(request.getParameter("i2Va30")));
                varxb.setI2Va31(Float.parseFloat(request.getParameter("i2Va31")));
                varxb.setI2Va32(Float.parseFloat(request.getParameter("i2Va32")));
                varxb.setI2Va33(Float.parseFloat(request.getParameter("i2Va33")));
                varxb.setI2Va34(Float.parseFloat(request.getParameter("i2Va34")));
                varxb.setI2Va35(Float.parseFloat(request.getParameter("i2Va35")));
                varxb.setI2Va36(Float.parseFloat(request.getParameter("i2Va36")));
                varxb.setI2Va37(Float.parseFloat(request.getParameter("i2Va37")));
                varxb.setI2Va38(Float.parseFloat(request.getParameter("i2Va38")));
                varxb.setI2Va39(Float.parseFloat(request.getParameter("i2Va39")));
                varxb.setI2Va40(Float.parseFloat(request.getParameter("i2Va40")));
                varxb.setI2Va41(Float.parseFloat(request.getParameter("i2Va41")));
                varxb.setI2Va42(Float.parseFloat(request.getParameter("i2Va42")));
                varxb.setI2Va43(Float.parseFloat(request.getParameter("i2Va43")));
                varxb.setI2Va44(Float.parseFloat(request.getParameter("i2Va44")));
                varxb.setI2Va45(Float.parseFloat(request.getParameter("i2Va45")));
                varxb.setI2Va46(Float.parseFloat(request.getParameter("i2Va46")));
                varxb.setI2Va47(Float.parseFloat(request.getParameter("i2Va47")));
                varxb.setI2Va48(Float.parseFloat(request.getParameter("i2Va48")));
                varxb.setI2Va49(Float.parseFloat(request.getParameter("i2Va49")));
                varxb.setI2Va50(Float.parseFloat(request.getParameter("i2Va50")));

                varxb.setI3Va2(Float.parseFloat(request.getParameter("i3Va2")));
                varxb.setI3Va3(Float.parseFloat(request.getParameter("i3Va3")));
                varxb.setI3Va4(Float.parseFloat(request.getParameter("i3Va4")));
                varxb.setI3Va5(Float.parseFloat(request.getParameter("i3Va5")));
                varxb.setI3Va6(Float.parseFloat(request.getParameter("i3Va6")));
                varxb.setI3Va7(Float.parseFloat(request.getParameter("i3Va7")));
                varxb.setI3Va8(Float.parseFloat(request.getParameter("i3Va8")));
                varxb.setI3Va9(Float.parseFloat(request.getParameter("i3Va9")));
                varxb.setI3Va10(Float.parseFloat(request.getParameter("i3Va10")));
                varxb.setI3Va11(Float.parseFloat(request.getParameter("i3Va11")));
                varxb.setI3Va12(Float.parseFloat(request.getParameter("i3Va12")));
                varxb.setI3Va13(Float.parseFloat(request.getParameter("i3Va13")));
                varxb.setI3Va14(Float.parseFloat(request.getParameter("i3Va14")));
                varxb.setI3Va15(Float.parseFloat(request.getParameter("i3Va15")));
                varxb.setI3Va16(Float.parseFloat(request.getParameter("i3Va16")));
                varxb.setI3Va17(Float.parseFloat(request.getParameter("i3Va17")));
                varxb.setI3Va18(Float.parseFloat(request.getParameter("i3Va18")));
                varxb.setI3Va19(Float.parseFloat(request.getParameter("i3Va19")));
                varxb.setI3Va20(Float.parseFloat(request.getParameter("i3Va20")));
                varxb.setI3Va21(Float.parseFloat(request.getParameter("i3Va21")));
                varxb.setI3Va22(Float.parseFloat(request.getParameter("i3Va22")));
                varxb.setI3Va23(Float.parseFloat(request.getParameter("i3Va23")));
                varxb.setI3Va24(Float.parseFloat(request.getParameter("i3Va24")));
                varxb.setI3Va25(Float.parseFloat(request.getParameter("i3Va25")));
                varxb.setI3Va26(Float.parseFloat(request.getParameter("i3Va26")));
                varxb.setI3Va27(Float.parseFloat(request.getParameter("i3Va27")));
                varxb.setI3Va28(Float.parseFloat(request.getParameter("i3Va28")));
                varxb.setI3Va29(Float.parseFloat(request.getParameter("i3Va29")));
                varxb.setI3Va30(Float.parseFloat(request.getParameter("i3Va30")));
                varxb.setI3Va31(Float.parseFloat(request.getParameter("i3Va31")));
                varxb.setI3Va32(Float.parseFloat(request.getParameter("i3Va32")));
                varxb.setI3Va33(Float.parseFloat(request.getParameter("i3Va33")));
                varxb.setI3Va34(Float.parseFloat(request.getParameter("i3Va34")));
                varxb.setI3Va35(Float.parseFloat(request.getParameter("i3Va35")));
                varxb.setI3Va36(Float.parseFloat(request.getParameter("i3Va36")));
                varxb.setI3Va37(Float.parseFloat(request.getParameter("i3Va37")));
                varxb.setI3Va38(Float.parseFloat(request.getParameter("i3Va38")));
                varxb.setI3Va39(Float.parseFloat(request.getParameter("i3Va39")));
                varxb.setI3Va40(Float.parseFloat(request.getParameter("i3Va40")));
                varxb.setI3Va41(Float.parseFloat(request.getParameter("i3Va41")));
                varxb.setI3Va42(Float.parseFloat(request.getParameter("i3Va42")));
                varxb.setI3Va43(Float.parseFloat(request.getParameter("i3Va43")));
                varxb.setI3Va44(Float.parseFloat(request.getParameter("i3Va44")));
                varxb.setI3Va45(Float.parseFloat(request.getParameter("i3Va45")));
                varxb.setI3Va46(Float.parseFloat(request.getParameter("i3Va46")));
                varxb.setI3Va47(Float.parseFloat(request.getParameter("i3Va47")));
                varxb.setI3Va48(Float.parseFloat(request.getParameter("i3Va48")));
                varxb.setI3Va49(Float.parseFloat(request.getParameter("i3Va49")));
                varxb.setI3Va50(Float.parseFloat(request.getParameter("i3Va50")));

                varxb.setU1Va1(defzero);
                varxb.setU2Va1(defzero);
                varxb.setU3Va1(defzero);
                varxb.setI1Va1(defzero);
                varxb.setI2Va1(defzero);
                varxb.setI3Va1(defzero);

                varxb.setThdu1(Float.parseFloat(request.getParameter("thdu1")));
                varxb.setThdu2(Float.parseFloat(request.getParameter("thdu2")));
                varxb.setThdu3(Float.parseFloat(request.getParameter("thdu3")));
                varxb.setThdi1(Float.parseFloat(request.getParameter("thdi1")));
                varxb.setThdi2(Float.parseFloat(request.getParameter("thdi2")));
                varxb.setThdi3(Float.parseFloat(request.getParameter("thdi3")));
            }


            try {
                if (var.getDid() != null) {
                    hbsessionDao.insert(var);
                }
                if (varxb.getDid() != null) {
                    hbsessionDao.insert(varxb);
                }

            } catch (Exception e) {
                e.printStackTrace();
                return "error";
            }

            boolean result = true;
        } catch (Exception e) {
            e.printStackTrace();
            return "error";
        }
        return "success";
    }

}
