
package webServiceAPI.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "getDataImpl", targetNamespace = "http://service.webServiceAPI/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetDataImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOnlineData", targetNamespace = "http://service.webServiceAPI/", className = "webserviceapi.service.GetOnlineData")
    @ResponseWrapper(localName = "getOnlineDataResponse", targetNamespace = "http://service.webServiceAPI/", className = "webserviceapi.service.GetOnlineDataResponse")
    @Action(input = "http://service.webServiceAPI/getDataImpl/getOnlineDataRequest", output = "http://service.webServiceAPI/getDataImpl/getOnlineDataResponse")
    public String getOnlineData(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

}
