package webServiceAPI.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "getDataImplService", targetNamespace = "http://service.webServiceAPI/", wsdlLocation = "http://192.168.1.253:8084/ws/onlinedatainterface?wsdl")
public class GetDataImplService
    extends Service
{

    private final static URL GETDATAIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETDATAIMPLSERVICE_EXCEPTION;
    private final static QName GETDATAIMPLSERVICE_QNAME = new QName("http://service.webServiceAPI/", "getDataImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.253:8084/ws/onlinedatainterface?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETDATAIMPLSERVICE_WSDL_LOCATION = url;
        GETDATAIMPLSERVICE_EXCEPTION = e;
    }

    public GetDataImplService() {
        super(__getWsdlLocation(), GETDATAIMPLSERVICE_QNAME);
    }

    public GetDataImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETDATAIMPLSERVICE_QNAME, features);
    }

    public GetDataImplService(URL wsdlLocation) {
        super(wsdlLocation, GETDATAIMPLSERVICE_QNAME);
    }

    public GetDataImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETDATAIMPLSERVICE_QNAME, features);
    }

    public GetDataImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetDataImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetDataImpl
     */
    @WebEndpoint(name = "getDataImplPort")
    public GetDataImpl getGetDataImplPort() {
        return super.getPort(new QName("http://service.webServiceAPI/", "getDataImplPort"), GetDataImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetDataImpl
     */
    @WebEndpoint(name = "getDataImplPort")
    public GetDataImpl getGetDataImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.webServiceAPI/", "getDataImplPort"), GetDataImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETDATAIMPLSERVICE_EXCEPTION!= null) {
            throw GETDATAIMPLSERVICE_EXCEPTION;
        }
        return GETDATAIMPLSERVICE_WSDL_LOCATION;
    }

}
